branch-defaults:
  default:
    environment: next-yoomy-web-page-env
    group_suffix: null
global:
  application_name: yoomy-web-page
  branch: null
  default_ec2_keyname: yoomywebpagekeypair
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
